export const detailData = {
  id: 5405902,
  objectID: 5405902,
  ownerID: 2094876,
  userExternalID: "2094876",
  sourceID: 1,
  state: "active",
  geography: {
    lat: 25.05383439,
    lng: 55.21216471,
  },
  purpose: "for-rent",
  price: 6999.0,
  product: "superhot",
  productLabel: "default",
  rentFrequency: "monthly",
  referenceNumber: "GMM-1BHK-AP313-MANI235",
  permitNumber: null,
  projectNumber: null,
  title: "FULLY FURNISHED 1BHK || READY TO MOVE IN || CALL US NOW",
  title_l1: "مفروشة بالكامل 1BHK || جاهز للانتقال للسكن || اتصل بنا الآن",
  title_l2:
    "位于朱美拉环形村(JVC)，JVC第12区，GMM1号 大厦 1 卧室的公寓 6999 AED - 8409290",
  title_l3:
    "Квартира в Джумейра Вилладж Серкл (ДЖВС)，JVC Дистрикт 12，Здание GMM 1, 1 спальня, 6999 AED - 8409290",
  description:
    "Peacefull Vacation Homes are proud to offer you a wonderful 1BHK apartment in GMM Tower, JVC. We set standards for new Luxurious Living in UAE. \n\nAmenities :-\n\nFully Furnished\nHuge Swimming Pool\nKids Playing Area\n24/7 Security\nParking\nSauna\nBarbeque Area\nModular-Kitchen\nCCTV &amp; Access Control Systems\nWaste Disposal\nService Elevators\nReception/Waiting Room\n\nWith its sustainable designed integrated technology, it provides the next level luxury living. Enjoying a prime location in the gated JVC community. Residents can quickly access famous attractions including Ibn Battuta Mall, Mall of Emirates and Dubai Marina Mall as well as commercial and residential hubs of Dubai like Jebel Ali Village, Jumeirah Lake Towers (JLT) and Dubai Marina. \n\nPeacefull Vacation Homes is a DTCM licensed Organization established by professionalism, integrity, accountability, and quality service giving you the most profitable Quick Rental Solutions today. \n\nWelcome to the Best Vacation Homes in Dubai.",
  description_l1:
    "تفتخر Peacefull Vacation Homes بأن تقدم لك شقة رائعة بغرفة نوم واحدة في برج GMM، قرية جميرا الدائرية. لقد وضعنا معايير جديدة للمعيشة الفاخرة في دولة الإمارات العربية المتحدة. \n\nوسائل الراحة :-\n\nمفروشة بالكامل\nحمام سباحة ضخم\nمنطقة لعب الاطفال\nأمن 24/7\nموقف سيارات\nساونا\nمنطقة الشواء\nوحدات المطبخ\nأنظمة الدوائر التلفزيونية المغلقة والتحكم في الوصول\nالتخلص من النفايات\nمصاعد الخدمة\nغرفة الاستقبال/الانتظار\n\nبفضل التكنولوجيا المتكاملة المصممة بشكل مستدام، فإنه يوفر المستوى التالي من المعيشة الفاخرة. استمتع بموقع متميز في مجتمع JVC المسور. يمكن للمقيمين الوصول بسرعة إلى مناطق الجذب الشهيرة بما في ذلك ابن بطوطة مول ومول الإمارات ودبي مارينا مول بالإضافة إلى المراكز التجارية والسكنية في دبي مثل قرية جبل علي وأبراج بحيرة الجميرا (JLT) ومرسى دبي. \n\nPeacefull Vacation Homes هي منظمة مرخصة من DTCM تم تأسيسها من خلال الاحتراف والنزاهة والمساءلة وجودة الخدمة مما يوفر لك حلول التأجير السريع الأكثر ربحية اليوم. \n\nمرحبًا بكم في أفضل بيوت العطلات في دبي.",
  description_l2:
    "Peacefull Vacation Homes are proud to offer you a wonderful 1BHK apartment in GMM Tower, JVC. We set standards for new Luxurious Living in UAE. \n\nAmenities :-\n\nFully Furnished\nHuge Swimming Pool\nKids Playing Area\n24/7 Security\nParking\nSauna\nBarbeque Area\nModular-Kitchen\nCCTV &amp; Access Control Systems\nWaste Disposal\nService Elevators\nReception/Waiting Room\n\nWith its sustainable designed integrated technology, it provides the next level luxury living. Enjoying a prime location in the gated JVC community. Residents can quickly access famous attractions including Ibn Battuta Mall, Mall of Emirates and Dubai Marina Mall as well as commercial and residential hubs of Dubai like Jebel Ali Village, Jumeirah Lake Towers (JLT) and Dubai Marina. \n\nPeacefull Vacation Homes is a DTCM licensed Organization established by professionalism, integrity, accountability, and quality service giving you the most profitable Quick Rental Solutions today. \n\nWelcome to the Best Vacation Homes in Dubai.",
  description_l3:
    "Peacefull Vacation Homes are proud to offer you a wonderful 1BHK apartment in GMM Tower, JVC. We set standards for new Luxurious Living in UAE. \n\nAmenities :-\n\nFully Furnished\nHuge Swimming Pool\nKids Playing Area\n24/7 Security\nParking\nSauna\nBarbeque Area\nModular-Kitchen\nCCTV &amp; Access Control Systems\nWaste Disposal\nService Elevators\nReception/Waiting Room\n\nWith its sustainable designed integrated technology, it provides the next level luxury living. Enjoying a prime location in the gated JVC community. Residents can quickly access famous attractions including Ibn Battuta Mall, Mall of Emirates and Dubai Marina Mall as well as commercial and residential hubs of Dubai like Jebel Ali Village, Jumeirah Lake Towers (JLT) and Dubai Marina. \n\nPeacefull Vacation Homes is a DTCM licensed Organization established by professionalism, integrity, accountability, and quality service giving you the most profitable Quick Rental Solutions today. \n\nWelcome to the Best Vacation Homes in Dubai.",
  externalID: "8409290",
  slug: "fully-furnished-1bhk-ready-to-move-in-call-us-now-8409290",
  slug_l1: "fully-furnished-1bhk-ready-to-move-in-call-us-now-8409290",
  slug_l2: "fully-furnished-1bhk-ready-to-move-in-call-us-now-8409290",
  slug_l3: "fully-furnished-1bhk-ready-to-move-in-call-us-now-8409290",
  location: [
    {
      id: 1,
      level: 0,
      externalID: "5001",
      name: "UAE",
      name_l1: "الإمارات",
      name_l2: "阿联酋",
      name_l3: "ОАЭ",
      slug: "/uae",
      slug_l1: "/uae",
      slug_l2: "/uae",
      slug_l3: "/uae",
    },
    {
      id: 2,
      level: 1,
      externalID: "5002",
      name: "Dubai",
      name_l1: "دبي",
      name_l2: "迪拜",
      name_l3: "Дубай",
      slug: "/dubai",
      slug_l1: "/dubai",
      slug_l2: "/dubai",
      slug_l3: "/dubai",
    },
    {
      id: 59,
      level: 2,
      externalID: "5416",
      name: "Jumeirah Village Circle (JVC)",
      name_l1: "قرية جميرا الدائرية",
      name_l2: "朱美拉环形村(JVC)",
      name_l3: "Джумейра Вилладж Серкл (ДЖВС)",
      slug: "/dubai/jumeirah-village-circle-jvc",
      slug_l1: "/dubai/jumeirah-village-circle-jvc",
      slug_l2: "/dubai/jumeirah-village-circle-jvc",
      slug_l3: "/dubai/jumeirah-village-circle-jvc",
      type: "neighbourhood",
    },
    {
      id: 1881,
      level: 3,
      externalID: "9536",
      name: "JVC District 12",
      name_l1: "الضاحية 12",
      name_l2: "JVC第12区",
      name_l3: "JVC Дистрикт 12",
      slug: "/dubai/jumeirah-village-circle-jvc/jvc-district-12",
      slug_l1: "/dubai/jumeirah-village-circle-jvc/jvc-district-12",
      slug_l2: "/dubai/jumeirah-village-circle-jvc/jvc-district-12",
      slug_l3: "/dubai/jumeirah-village-circle-jvc/jvc-district-12",
      type: "neighbourhood",
    },
    {
      id: 17814,
      level: 4,
      externalID: "13586",
      name: "GMM Tower 1",
      name_l1: "GMM 1 تاور",
      name_l2: "GMM1号 大厦 ",
      name_l3: "Здание GMM 1",
      slug: "/dubai/jumeirah-village-circle-jvc/jvc-district-12/gmm-tower-1",
      slug_l1: "/dubai/jumeirah-village-circle-jvc/jvc-district-12/gmm-tower-1",
      slug_l2: "/dubai/jumeirah-village-circle-jvc/jvc-district-12/gmm-tower-1",
      slug_l3: "/dubai/jumeirah-village-circle-jvc/jvc-district-12/gmm-tower-1",
      type: "condo-building",
    },
  ],
  category: [
    {
      id: 1,
      level: 0,
      externalID: "1",
      name: "Residential",
      name_l1: "سكني",
      name_l2: "居住物业",
      name_l3: "Жилые",
      slug: "residential",
      slug_l1: "residential",
      slug_l2: "residential",
      slug_l3: "residential",
      nameSingular: "Residential",
      nameSingular_l1: "سكني",
      nameSingular_l2: "居住物业",
      nameSingular_l3: "Жилые",
    },
    {
      id: 2,
      level: 1,
      externalID: "4",
      name: "Apartments",
      name_l1: "شقق",
      name_l2: "公寓",
      name_l3: "Апартаменты",
      slug: "apartments",
      slug_l1: "apartments",
      slug_l2: "apartments",
      slug_l3: "apartments",
      nameSingular: "Apartment",
      nameSingular_l1: "شقة",
      nameSingular_l2: "公寓",
      nameSingular_l3: "Квартира",
    },
  ],
  createdAt: 1704435572.0,
  approvedAt: 1704435572.0,
  updatedAt: 1704526805.0,
  touchedAt: 1704685247.091575,
  reactivatedAt: 1704435572.0,
  rooms: 1,
  baths: 2,
  area: 69.67728000000001,
  score: 75,
  score_l1: 75,
  score_l2: 75,
  score_l3: 75,
  coverPhoto: {
    id: 571700588,
    externalID: "163391274",
    title: "WhatsApp Image 2024-01-04 at 6.16. 03 PM. jpeg",
    orderIndex: 0,
    nimaScore: 9.405619736545475,
    url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/571700588/c042883c0f674630a7cf89fb8a87d946",
    main: true,
  },
  photoCount: 11,
  videoCount: 0,
  panoramaCount: 0,
  photos: [
    {
      id: 571700588,
      externalID: "163391274",
      title: "WhatsApp Image 2024-01-04 at 6.16. 03 PM. jpeg",
      orderIndex: 0,
      nimaScore: 9.405619736545475,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/571700588/c042883c0f674630a7cf89fb8a87d946",
    },
    {
      id: 571700589,
      externalID: "163391275",
      title: "WhatsApp Image 2024-01-04 at 6.16. 04 PM. jpeg",
      orderIndex: 1,
      nimaScore: 9.602124983373017,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/571700589/9ac30ea647dd45bc9e134a41156bcd00",
    },
    {
      id: 571700590,
      externalID: "163391276",
      title: "WhatsApp Image 2024-01-04 at 6.16. 05 PM. jpeg",
      orderIndex: 2,
      nimaScore: 9.180331467979158,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/571700590/40eb53718927482d9dc5def5c021bfd8",
    },
    {
      id: 571700591,
      externalID: "163391277",
      title: "WhatsApp Image 2024-01-04 at 6.16. 04 PM (1). jpeg",
      orderIndex: 3,
      nimaScore: 8.750750823381168,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/571700591/cac89dba59d24bc68e192e0656ee3fa3",
    },
    {
      id: 571700592,
      externalID: "163391278",
      title: "WhatsApp Image 2024-01-04 at 6.16. 07 PM (1). jpeg",
      orderIndex: 4,
      nimaScore: 8.62490495729071,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/571700592/444bbc83d96e40c9b8ed3a004169ff38",
    },
    {
      id: 571700593,
      externalID: "163391279",
      title: "WhatsApp Image 2024-01-04 at 6.16. 07 PM. jpeg",
      orderIndex: 5,
      nimaScore: 8.97010024804149,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/571700593/42affd36938d405081f6c135055a8a2c",
    },
    {
      id: 571700594,
      externalID: "163391280",
      title: "WhatsApp Image 2024-01-04 at 6.16. 02 PM. jpeg",
      orderIndex: 6,
      nimaScore: 8.261426369794208,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/571700594/a8b9d530c2974ce19e21f021f520e22e",
    },
    {
      id: 571700595,
      externalID: "163391281",
      title: "WhatsApp Image 2024-01-04 at 6.16. 02 PM (1). jpeg",
      orderIndex: 7,
      nimaScore: 7.9918754524208,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/571700595/ef2981443155459da0c763dfebd06849",
    },
    {
      id: 571700596,
      externalID: "163391282",
      title: "WhatsApp Image 2024-01-04 at 6.16. 06 PM (1). jpeg",
      orderIndex: 8,
      nimaScore: 8.67318422679,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/571700596/5ffda89db747491bab1e96ce21c6b0e1",
    },
    {
      id: 571700597,
      externalID: "163391283",
      title: "WhatsApp Image 2024-01-04 at 6.16. 06 PM. jpeg",
      orderIndex: 9,
      nimaScore: 6.037622339230026,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/571700597/56e1a5360320406a81fdddaada8dbf6d",
    },
    {
      id: 571700598,
      externalID: "163391284",
      title: "WhatsApp Image 2024-01-04 at 6.16. 07 PM (2). jpeg",
      orderIndex: 10,
      nimaScore: 6.041886413957144,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/571700598/3d090bdda60d43fb8ace91f65c5ad415",
    },
  ],
  floorPlans: [],
  videos: [],
  panoramas: [],
  amenities: [
    {
      externalGroupID: 9,
      groupRank: 1,
      text: "Features",
      text_l1: "مزايا",
      text_l2: "日托中心",
      text_l3: "Характеристики",
      amenities: [
        {
          text: "Furnished",
          text_l1: "مفروشة",
          text_l2: "配备家具",
          text_l3: "Меблированный",
          value: "True",
          rank: 1,
          slug: "furnished",
          format: "checkbox",
          externalID: 20,
        },
        {
          text: "Electricity Backup",
          text_l1: "نظام كهرباء احتياطي للطوارئ",
          text_l2: "备用电力",
          text_l3: "Резервное электричество",
          value: "True",
          rank: 2,
          slug: "electricity-backup",
          format: "checkbox",
          externalID: 10,
        },
        {
          text: "Centrally Air-Conditioned",
          text_l1: "نظام تبريد مركزي",
          text_l2: "中央空调",
          text_l3: "Центральное кондиционирование",
          value: "True",
          rank: 4,
          slug: "centrally-air-conditioned",
          format: "checkbox",
          externalID: 7,
        },
        {
          text: "Double Glazed Windows",
          text_l1: "نوافذ زجاجية مزدوجة",
          text_l2: "双层玻璃窗",
          text_l3: "Окна с двойным остеклением",
          value: "True",
          rank: 6,
          slug: "double-glazed-windows",
          format: "checkbox",
          externalID: 6,
        },
      ],
    },
    {
      externalGroupID: 5,
      groupRank: 2,
      text: "Building",
      text_l1: "البناء",
      text_l2: "入户大堂",
      text_l3: "Здание",
      amenities: [
        {
          text: "Balcony or Terrace",
          text_l1: "شرفة أو تراس",
          text_l2: "阳台",
          text_l3: "Балкон или терраса",
          value: "True",
          rank: 1,
          slug: "balcony-or-terrace",
          format: "checkbox",
          externalID: 3,
        },
        {
          text: "Lobby in Building",
          text_l1: "ردهة إستقبال",
          text_l2: "入户大堂",
          text_l3: "Лобби в здании",
          value: "True",
          rank: 2,
          slug: "lobby-in-building",
          format: "checkbox",
          externalID: 5,
        },
        {
          text: "Service Elevators",
          text_l1: "خدمات المصاعد",
          text_l2: "服务电梯",
          text_l3: "Служебные лифты",
          value: "True",
          rank: 4,
          slug: "service-elevators",
          format: "checkbox",
          externalID: 17,
        },
        {
          text: "Prayer Room",
          text_l1: "غرفة صلاة",
          text_l2: "祈祷室",
          text_l3: "Молитвенная комната",
          value: "True",
          rank: 7,
          slug: "prayer-room",
          format: "checkbox",
          externalID: 23,
        },
        {
          text: "Reception/Waiting Room",
          text_l1: "غرفة استقبال /انتظار",
          text_l2: "桑拿",
          text_l3: "Прием/Зал ожидания",
          value: "True",
          rank: 8,
          slug: "receptionwaiting-room",
          format: "checkbox",
          externalID: 41,
        },
      ],
    },
    {
      externalGroupID: 3,
      groupRank: 3,
      text: "Health and Fitness",
      text_l1: "الصحة و اللياقة",
      text_l2: "阳台",
      text_l3: "Здоровье и Фитнесс",
      amenities: [
        {
          text: "Gym or Health Club",
          text_l1: "صالة رياضية أو نادي صحي",
          text_l2: "健身房或健身俱乐部",
          text_l3: "Тренажерный зал или оздоровительный клуб",
          value: "True",
          rank: 3,
          slug: "gym-or-health-club",
          format: "checkbox",
          externalID: 22,
        },
        {
          text: "Swimming Pool",
          text_l1: "مسبح",
          text_l2: "附近医院",
          text_l3: "Бассейн",
          value: "True",
          rank: 6,
          slug: "swimming-pool",
          format: "checkbox",
          externalID: 45,
        },
        {
          text: "Jacuzzi",
          text_l1: "جاكوزي",
          text_l2: "按摩浴缸",
          text_l3: "Джакузи",
          value: "True",
          rank: 9,
          slug: "jacuzzi",
          format: "checkbox",
          externalID: 33,
        },
        {
          text: "Sauna",
          text_l1: "ساونا",
          text_l2: "汗蒸房",
          text_l3: "Сауна",
          value: "True",
          rank: 10,
          slug: "sauna",
          format: "checkbox",
          externalID: 42,
        },
        {
          text: "Steam Room",
          text_l1: "غرفة بخار",
          text_l2: "游泳池",
          text_l3: "Паровая комната",
          value: "True",
          rank: 12,
          slug: "steam-room",
          format: "checkbox",
          externalID: 43,
        },
      ],
    },
    {
      externalGroupID: 2,
      groupRank: 4,
      text: "Recreation and Family",
      text_l1: "الترفيه والأسرة",
      text_l2: "景观",
      text_l3: "Отдых и семья",
      amenities: [
        {
          text: "Day Care Center",
          text_l1: "مركز رعاية أطفال",
          text_l2: "日托中心",
          text_l3: "Детский сад",
          value: "True",
          rank: 2,
          slug: "day-care-center",
          format: "checkbox",
          externalID: 9,
        },
        {
          text: "Kids Play Area",
          text_l1: "منطقة لعب للأطفال",
          text_l2: "儿童娱乐区",
          text_l3: "Детская игровая площадка",
          value: "True",
          rank: 3,
          slug: "kids-play-area",
          format: "checkbox",
          externalID: 34,
        },
        {
          text: "Lawn or Garden",
          text_l1: "حديقة",
          text_l2: "绿化",
          text_l3: "Газон или сад",
          value: "True",
          rank: 5,
          slug: "lawn-or-garden",
          format: "checkbox",
          externalID: 36,
        },
        {
          text: "Barbeque Area",
          text_l1: "مكان مخصص للشواء",
          text_l2: "烧烤区",
          text_l3: "Зона барбекю",
          value: "True",
          rank: 7,
          slug: "barbeque-area",
          format: "checkbox",
          externalID: 4,
        },
        {
          text: "Cafeteria or Canteen",
          text_l1: "كافيتيريا",
          text_l2: "自助餐厅或食堂",
          text_l3: "Кафетерий или столовая",
          value: "True",
          rank: 9,
          slug: "cafeteria-or-canteen",
          format: "checkbox",
          externalID: 64,
        },
      ],
    },
    {
      externalGroupID: 10,
      groupRank: 5,
      text: "Cleaning and Maintenance",
      text_l1: "التنظيف والصيانة",
      text_l2: "备用电力",
      text_l3: "Очистка и тех. обслуживание",
      amenities: [
        {
          text: "Waste Disposal",
          text_l1: "مكبّ نفايات",
          text_l2: "垃圾处理",
          text_l3: "Утилизация отходов",
          value: "True",
          rank: 1,
          slug: "waste-disposal",
          format: "checkbox",
          externalID: 11,
        },
        {
          text: "Maintenance Staff",
          text_l1: "خدمات صيانة",
          text_l2: "清洁服务",
          text_l3: "Обслуживающий персонал",
          value: "True",
          rank: 2,
          slug: "maintenance-staff",
          format: "checkbox",
          externalID: 61,
        },
        {
          text: "Cleaning Services",
          text_l1: "خدمات تنظيف",
          text_l2: "清洁服务",
          text_l3: "Услуги по уборке",
          value: "True",
          rank: 3,
          slug: "cleaning-services",
          format: "checkbox",
          externalID: 73,
        },
      ],
    },
    {
      externalGroupID: 6,
      groupRank: 6,
      text: "Business and Security",
      text_l1: "الأعمال والأمن والحماية",
      text_l2: "双层玻璃窗",
      text_l3: "Бизнес и безопасность",
      amenities: [
        {
          text: "Conference Room",
          text_l1: "غرفة اجتماعات",
          text_l2: "会议室",
          text_l3: "Конференц-зал",
          value: "True",
          rank: 2,
          slug: "conference-room",
          format: "checkbox",
          externalID: 29,
        },
        {
          text: "Security Staff",
          text_l1: "أمن و حماية",
          text_l2: "全部楼层",
          text_l3: "Сотрудники безопасности",
          value: "True",
          rank: 3,
          slug: "security-staff",
          format: "checkbox",
          externalID: 62,
        },
        {
          text: "CCTV Security",
          text_l1: "نظام كاميرات مراقبة",
          text_l2: "闭路电视安全",
          text_l3: "Безопасность видеонаблюдения",
          value: "True",
          rank: 4,
          slug: "cctv-security",
          format: "checkbox",
          externalID: 63,
        },
      ],
    },
    {
      externalGroupID: 4,
      groupRank: 7,
      text: "Laundry and Kitchen",
      text_l1: "الغسيل والمطبخ",
      text_l2: "烧烤区",
      text_l3: "Прачечная и кухня",
      amenities: [
        {
          text: "Laundry Facility",
          text_l1: "خدمة غسيل ملابس",
          text_l2: "洗衣设施",
          text_l3: "прачечная",
          value: "True",
          rank: 3,
          slug: "laundry-facility",
          format: "checkbox",
          externalID: 65,
        },
      ],
    },
    {
      externalGroupID: 8,
      groupRank: 8,
      text: "Technology",
      text_l1: "الخدمات التقنية",
      text_l2: "中央供暖",
      text_l3: "Технологии",
      amenities: [
        {
          text: "Broadband Internet",
          text_l1: "انترنت واسع النطاق",
          text_l2: "宽带网络",
          text_l3: "Широкополосный интернет",
          value: "True",
          rank: 1,
          slug: "broadband-internet",
          format: "checkbox",
          externalID: 26,
        },
        {
          text: "Satellite/Cable TV",
          text_l1: "كابل قنوات تلفزيونية",
          text_l2: "卫星电视/有线电视",
          text_l3: "Спутниковое/кабельное телевидение",
          value: "True",
          rank: 2,
          slug: "satellitecable-tv",
          format: "checkbox",
          externalID: 27,
        },
      ],
    },
    {
      externalGroupID: 7,
      groupRank: 9,
      text: "Miscellaneous",
      text_l1: "الخدمات العامة",
      text_l2: "中央空调",
      text_l3: "Разное",
      amenities: [
        {
          text: "ATM Facility",
          text_l1: "توفر أجهزة السحب الآلي",
          text_l2: "自动取款机",
          text_l3: "Банкомат",
          value: "True",
          rank: 1,
          slug: "atm-facility",
          format: "checkbox",
          externalID: 31,
        },
        {
          text: "24 Hours Concierge",
          text_l1: "حراسة 24 ساعة",
          text_l2: "24小时礼宾服务",
          text_l3: "Круглосуточный консьерж",
          value: "True",
          rank: 2,
          slug: "24-hours-concierge",
          format: "checkbox",
          externalID: 72,
        },
        {
          text: "Pet Policy",
          text_l1: "دخول الحيوانات الأليفة",
          text_l2: "宠物管理",
          text_l3: "Политика домашних животных",
          value: "Allowed",
          rank: 3,
          slug: "pet-policy",
          format: "select",
          externalID: 21,
        },
        {
          text: "Nearby Shopping Malls",
          text_l1: "مراكز تسوق قريبة",
          text_l2: "泊车位",
          text_l3: "Ближайшие торговые центры",
          value: "Circle Mall",
          rank: 12,
          slug: "nearby-shopping-malls",
          format: "text",
          externalID: 57,
        },
        {
          text: "Freehold",
          text_l1: "التملك الحر",
          text_l2: "永久产权",
          text_l3: "Право собственности",
          value: "True",
          rank: 23,
          slug: "freehold",
          format: "checkbox",
          externalID: 19,
        },
      ],
    },
  ],
  phoneNumber: {
    mobile: "+971529407235",
    phone: "+97145539027",
    whatsapp: "971545695868",
    phoneNumbers: ["+97145539027"],
    mobileNumbers: ["+971529407235"],
  },
  contactName: "Salman Mani",
  agency: {
    id: 29583084,
    objectID: 29583084,
    name: "Peace Full Vacation Homes",
    name_l1: "بيس فول لتأجير بيوت العطلات",
    name_l2: "Peace Full Vacation Homes",
    name_l3: "Peace Full Vacation Homes",
    externalID: "9945",
    product: "premium",
    productScore: 2,
    licenses: [
      {
        number: "761913",
        authority: "DED",
      },
    ],
    logo: {
      id: 95887451,
      url: "https://bayut-production.s3.eu-central-1.amazonaws.com/image/95887451/dd511fdbc2e84cbe9963123840177a97",
    },
    slug: "peace-full-vacation-homes-9945",
    slug_l1: "peace-full-vacation-homes-9945",
    slug_l2: "peace-full-vacation-homes-9945",
    slug_l3: "peace-full-vacation-homes-9945",
    tr: 3,
    tier: 3,
    roles: [],
    active: true,
    createdAt: "2020-09-22T08:48:39+00:00",
    commercialNumber: null,
    shortNumber: null,
    performanceCohort: "overachieving",
  },
  active: true,
  hasExactGeography: true,
  verification: {
    status: "verified",
    type: null,
    eligible: true,
    comment: null,
    updatedAt: 1704443023.825922,
    verifiedAt: 1704443018.0,
    visitedAt: null,
    trucheckedAt: 1704443018.0,
  },
  isVerified: true,
  completionStatus: "completed",
  occupancyStatus: "vacant",
  randBoostScore: 715,
  randBoostScore_l1: 715,
  randBoostScore_l2: 586,
  randBoostScore_l3: 586,
  furnishingStatus: "furnished",
  extraFields: {},
  type: "property",
  cityLevelScore: 1,
  indyScore: 715,
  indyScore_l1: 715,
  indyScore_l2: 586,
  indyScore_l3: 586,
  hasMatchingFloorPlans: false,
  hidePrice: false,
  locationPurposeTier: 1,
  plotArea: null,
};
